export const OrchidsData = [
  {
    id: "1",
    name: "Taichung beauty",
    rating: "5",
    isSpecial: "true",
    isNatuaral: "false",
    img: "https://barritaorchids.com/cdn/shop/products/Cf592_1024x1024.jpg",
    color: "pink",
    numberOfLike: "192",
    origin: "Taiwan",
    category: "Cattleya",
  },
  {
    id: "2",
    name: "Dendrobium Stardust",
    rating: "4.8",
    isSpecial: "true",
    isNatuaral: "false",
    img: "https://cdn11.bigcommerce.com/s-pxrevx9n0f/images/stencil/1280x1280/products/3747/18654/IMG_0339S__66292.1680813778.JPG?c=2",
    color: "orange",
    numberOfLike: "158",
    origin: "Thailand",
    category: "Dendrobium",
  },
  {
    id: "3",
    name: "Phalaenopsis Sogo Yukidian",
    rating: "5",
    isSpecial: "true",
    isNatuaral: "false",
    img: "https://whiteplainsorchids.com/wp-content/uploads/2020/03/20200322_175725-scaled.jpg",
    color: "white",
    numberOfLike: "245",
    origin: "Taiwan",
    category: "Phalaenopsis",
  },
  {
    id: "4",
    name: "Cymbidium ensifolium",
    rating: "4.7",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://upload.wikimedia.org/wikipedia/commons/f/f3/Cymbidium_ensifolium_%27%E7%BF%A0%E7%8E%89%27.jpg",
    color: "green",
    numberOfLike: "97",
    origin: "China",
    category: "Cymbidium",
  },
  {
    id: "5",
    name: "Vanda coerulea",
    rating: "4.9",
    isSpecial: "true",
    isNatuaral: "true",
    img: "https://storage.googleapis.com/powop-assets/kew_profiles/KPPCONT_051807_fullsize.jpg",
    color: "blue",
    numberOfLike: "211",
    origin: "India",
    category: "Vanda",
  },
  {
    id: "6",
    name: "Oncidium Sharry Baby",
    rating: "4.6",
    isSpecial: "true",
    isNatuaral: "false",
    img: "https://i.ebayimg.com/images/g/1FEAAOSwSGJl9vPM/s-l1200.jpg",
    color: "red",
    numberOfLike: "178",
    origin: "USA",
    category: "Oncidium",
  },
  {
    id: "7",
    name: "Miltoniopsis Herralexandre",
    rating: "4.5",
    isSpecial: "false",
    isNatuaral: "false",
    img: "https://cdn11.bigcommerce.com/s-ookf1bkiza/products/23908/images/32664/c7ea6bda-351a-481e-a15f-1da4e6dc5117__05564.1717101668.386.513.jpg?c=2",
    color: "purple",
    numberOfLike: "102",
    origin: "Colombia",
    category: "Miltoniopsis",
  },
  {
    id: "8",
    name: "Paphiopedilum delenatii",
    rating: "4.8",
    isSpecial: "true",
    isNatuaral: "true",
    img: "https://orchids-shop.com/cdn/shop/products/5017-a-pap.jpg?v=1680599927",
    color: "pink",
    numberOfLike: "198",
    origin: "Vietnam",
    category: "Paphiopedilum",
  },
  {
    id: "9",
    name: "Cattleya walkeriana",
    rating: "4.9",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://shrubz.us/wp-content/uploads/2019/08/Cattleya_walkeriana_flamea_divina_02.jpeg",
    color: "lavender",
    numberOfLike: "156",
    origin: "Brazil",
    category: "Cattleya",
  },
  {
    id: "10",
    name: "Brassia Rex",
    rating: "4.4",
    isSpecial: "false",
    isNatuaral: "false",
    img: "https://ecuageneraus.com/cdn/shop/files/1_7ded1ec1-609c-4e30-bdab-e374473ad531.jpg?v=1731169938",
    color: "yellow",
    numberOfLike: "89",
    origin: "Honduras",
    category: "Brassia",
  },
  {
    id: "11",
    name: "Ludisia discolor",
    rating: "4.3",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://ekkekzo4n8t.exactdn.com/wp-content/uploads/2024/11/IMG_9373.jpg?strip=all&lossy=1&sharp=1&ssl=1",
    color: "dark red",
    numberOfLike: "76",
    origin: "Southeast Asia",
    category: "Ludisia",
  },
  {
    id: "12",
    name: "Coelogyne cristata",
    rating: "4.6",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://www.akerne-orchids.com/953-large_default/coelogyne-cristata.jpg",
    color: "white",
    numberOfLike: "103",
    origin: "Nepal",
    category: "Coelogyne",
  },
  {
    id: "13",
    name: "Renanthera imschootiana",
    rating: "4.8",
    isSpecial: "true",
    isNatuaral: "true",
    img: "https://sweetgumandpines.wordpress.com/wp-content/uploads/2020/05/ren_imschootiana1.jpg?w=640",
    color: "scarlet",
    numberOfLike: "132",
    origin: "Vietnam",
    category: "Renanthera",
  },
  {
    id: "14",
    name: "Zygopetalum maxillare",
    rating: "4.5",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://sproutsofbristol.co.uk/cdn/shop/products/orchid-zygopetalum-maxillare-372951.jpg?v=1683194837&width=480",
    color: "mottled green-purple",
    numberOfLike: "95",
    origin: "Brazil",
    category: "Zygopetalum",
  },
  {
    id: "15",
    name: "Aerangis articulata",
    rating: "4.7",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://i.ebayimg.com/images/g/iAAAAOSwwwRa5I9G/s-l400.jpg",
    color: "white",
    numberOfLike: "82",
    origin: "Madagascar",
    category: "Aerangis",
  },
  {
    id: "16",
    name: "Encyclia cochleata",
    rating: "4.4",
    isSpecial: "false",
    isNatuaral: "true",
    img: "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/A_and_B_Larsen_orchids_-_Encyclia_cochleata_682-23.jpg/640px-A_and_B_Larsen_orchids_-_Encyclia_cochleata_682-23.jpg",
    color: "green-purple",
    numberOfLike: "79",
    origin: "Central America",
    category: "Encyclia",
  },
];
